
# Application Settings

# copies of the system should run
replicaCount: 3

# Alpine Docker Box
image:
  repository: dilukshi1017/airtrack-api
  tag: "latest"


# Networking Settings

service:
  type: ClusterIP
  port: 8080
