apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  # check with values.yaml file to see what type of door to build
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
  selector:
    app: airtrack
